version: '3.1'
services:
  db:
    image: "postgres:15"
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adm123
      POSTGRES_DB: wo
